-- yinkai_web 官网数据库结构(MySQL 8.0+,utf8mb4)
-- 内容数据双语列统一用 _zh/_en 后缀;image 存素材文件名,由前端资源表解析为实际 URL

CREATE DATABASE IF NOT EXISTS yinkai_web
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE yinkai_web;

-- 新闻
CREATE TABLE IF NOT EXISTS news (
  id INT PRIMARY KEY,
  tag_zh VARCHAR(50) NOT NULL,
  tag_en VARCHAR(50) NOT NULL,
  news_date DATE NOT NULL,
  title_zh VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  summary_zh VARCHAR(500) NOT NULL,
  summary_en VARCHAR(500) NOT NULL,
  content_zh MEDIUMTEXT NOT NULL,
  content_en MEDIUMTEXT NOT NULL,
  is_published TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 职位
CREATE TABLE IF NOT EXISTS jobs (
  id INT PRIMARY KEY,
  title_zh VARCHAR(100) NOT NULL,
  title_en VARCHAR(100) NOT NULL,
  dept_zh VARCHAR(100) NOT NULL,
  dept_en VARCHAR(100) NOT NULL,
  location_zh VARCHAR(100) NOT NULL,
  location_en VARCHAR(100) NOT NULL,
  desc_zh MEDIUMTEXT NOT NULL,
  desc_en MEDIUMTEXT NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 产品分类
CREATE TABLE IF NOT EXISTS product_categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(50) NOT NULL UNIQUE,
  name_zh VARCHAR(100) NOT NULL,
  name_en VARCHAR(100) NOT NULL,
  desc_zh VARCHAR(500) NOT NULL,
  desc_en VARCHAR(500) NOT NULL,
  sort INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 产品(图片存文件名,前端映射到打包资源)
CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  category_id INT NOT NULL,
  model VARCHAR(100) NOT NULL,
  tag_zh VARCHAR(100) NOT NULL,
  tag_en VARCHAR(100) NOT NULL,
  image VARCHAR(255) NOT NULL,
  gallery JSON NULL,
  desc_zh MEDIUMTEXT NOT NULL,
  desc_en MEDIUMTEXT NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES product_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 产品参数(一对多挂产品)
CREATE TABLE IF NOT EXISTS product_params (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_id INT NOT NULL,
  label_zh VARCHAR(100) NOT NULL,
  label_en VARCHAR(100) NOT NULL,
  value_zh VARCHAR(255) NOT NULL,
  value_en VARCHAR(255) NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_params_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 公司荣誉
CREATE TABLE IF NOT EXISTS honors (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name_zh VARCHAR(100) NOT NULL,
  name_en VARCHAR(100) NOT NULL,
  desc_zh VARCHAR(500) NOT NULL,
  desc_en VARCHAR(500) NOT NULL,
  image VARCHAR(255) NOT NULL,
  sort INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 合作伙伴
CREATE TABLE IF NOT EXISTS partners (
  id INT PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(50) NOT NULL UNIQUE,
  name_zh VARCHAR(100) NOT NULL,
  name_en VARCHAR(100) NOT NULL,
  image VARCHAR(255) NOT NULL,
  sort INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
