-- yinkai_web 种子数据(来源:src/data/index.js,2026-09-29)
USE yinkai_web;

-- ---- 新闻 ----
INSERT INTO news (id, tag_zh, tag_en, news_date, title_zh, title_en, summary_zh, summary_en, content_zh, content_en) VALUES
(1,'公司动态','Company News','2026-08-20','寅铠光伏边框自动生产线再获海外订单','Yinkai Wins Another Overseas Order for PV Frame Production Lines','海外客户对 ±0.1mm 加工精度与数秒级节拍给予高度认可。','The overseas customer highly recognized the ±0.1mm precision and second-level cycle time.','近日，寅铠与海外客户签订光伏边框自动生产线订单。该产线延续 YK 系列模块化设计，集自动上料、切割、冲孔、铆压于一体，节拍最快数秒一支，切割与孔距精度达 ±0.1mm。客户表示，寅铠设备的高稳定性与快速换型能力是本次合作的关键因素。','Yinkai recently signed an order for PV frame production lines with an overseas customer. Continuing the modular YK series design, the line integrates auto feeding, cutting, punching and riveting with a cycle of seconds per frame and ±0.1mm precision. The customer cited Yinkai''s stability and fast changeover as key factors.'),
(2,'技术迭代','Technology','2026-05-12','YK-OL 在线视觉检测系统完成新一轮迭代升级','New Iteration of the YK-OL Inline Vision Inspection System Released','检测节拍提升至 1.7 秒以内，新增多类瑕疵识别模型。','Cycle improved to under 1.7 seconds with new defect recognition models.','寅铠研发团队完成 YK-OL 系列在线视觉检测系统新一轮迭代。系统可在线检测长度、扭曲度、漏加工及碰伤、划伤、变形、脏污、铝屑等十余类外观瑕疵并自动分拣，节拍 ≤1.7 秒，换型时间 ≤20 分钟，检测数据可保存追溯，进一步巩固了公司在光伏边框检测领域的技术优势。','Yinkai''s R&D team completed a new iteration of the YK-OL inline vision inspection system. It inspects length, twist, missed operations and over a dozen surface defects (dents, scratches, deformation, dirt, aluminum chips) with auto sorting at ≤1.7s cycle and ≤20min changeover, with traceable data storage, reinforcing Yinkai''s technical edge in PV frame inspection.'),
(3,'项目交付','Project Delivery','2026-03-02','美国光伏边框产线项目顺利通过终验收','US PV Frame Line Project Passes Final Acceptance','涵盖边框生产与在线视觉尺寸检测的整线方案获客户认可。','The complete line with production and inline dimension inspection was accepted by the customer.','寅铠为美国客户提供的光伏边框生产与视觉检测设备项目顺利通过终验收。项目包含边框自动生产线与在线视觉尺寸检测工位，采用 2500 万像素远心镜头双相机进行直线度与弯扭检测，检测数据以 Excel 保存并可追溯。这标志着寅铠光伏装备的国际化交付能力再上台阶。','Yinkai''s PV frame production and vision inspection equipment project for a US customer passed final acceptance. The project included an automatic frame line and an inline dimension inspection station with dual 25MP telecentric cameras for straightness and bend/twist detection, with Excel-exported traceable data — another milestone in Yinkai''s global delivery capability.'),
(4,'展会活动','Exhibitions','2025-11-15','寅铠亮相国际光伏装备展会','Yinkai Exhibited at an International PV Equipment Show','现场展示光伏边框自动生产线核心技术方案。','Showcased core technologies of the PV frame production line on site.','寅铠携光伏边框自动生产线核心技术方案亮相行业展会，重点展示弹性夹具系统、旋转切割刀头等自主技术，以及“切冲铆一气呵成”的整线设计理念，吸引众多国内外客户驻足交流。','Yinkai showcased its PV frame production line technologies at an industry expo, highlighting proprietary innovations such as the elastic clamping system and rotary cutting head, and the one-flow cutting-punching-riveting line concept, attracting many domestic and international customers.'),
(5,'质量体系','Quality','2025-06-18','公司通过 ISO9001 质量管理体系换版审核','Yinkai Passed the ISO9001 Recertification Audit','自 2005 年首次认证以来持续保持质量体系有效运行。','Maintaining an effective quality system since first certification in 2005.','寅铠顺利通过 ISO9001 质量管理体系换版审核。公司自 2005 年获得德国莱茵 TÜV 颁发的 ISO9001 认证以来，始终严格执行质量管理体系标准，为汽车与光伏两大行业客户提供稳定可靠的装备与服务。','Yinkai passed the ISO9001 recertification audit. Since first receiving ISO9001 from TÜV Rheinland in 2005, the company has strictly maintained its quality management system, providing reliable equipment and services to customers in both automotive and PV industries.'),
(6,'公司动态','Company News','2025-01-10','汽车焊装业务稳步推进，多条产线同步交付','Steady Progress in Automotive BIW Business with Multiple Lines Delivered','延续大众、通用等主机厂长期合作关系。','Continuing long-term partnerships with OEMs such as VW and GM.','寅铠汽车白车身焊装业务保持稳健发展，年内多条焊装线、分拼线及工装夹具项目按期交付。公司自 2004 年成立以来累计服务上海大众、上海通用、上汽、吉利、长城等众多主机厂与一级供应商，以宝马级制造标准赢得行业口碑。','Yinkai''s BIW welding business remained solid, with multiple welding lines, hemming lines and fixture projects delivered on schedule this year. Since 2004, Yinkai has served many OEMs and Tier-1 suppliers including SVW, SGM, SAIC, Geely and Great Wall, earning industry recognition with BMW-grade manufacturing standards.'),
(7,'项目交付','Project Delivery','2024-09-26','东南亚光伏组件基地边框产线完成验收','PV Frame Lines for Southeast Asia Module Plant Passed Acceptance','海外第二基地建设再下一城，产线稼动率达 98%。','Another overseas milestone with line uptime reaching 98%.','寅铠为东南亚某大型光伏组件基地提供的边框自动生产线项目完成终验收。产线涵盖自动上料、切割、冲孔、铆压与在线检测全流程，投产后稼动率达 98%，单线日产能满足组件基地配套需求。客户对设备的稳定性与寅铠工程师团队的远程支持能力给予高度评价，双方就后续二期扩产达成初步合作意向。','The PV frame automatic lines supplied by Yinkai for a large module plant in Southeast Asia passed final acceptance. Covering auto feeding, cutting, punching, riveting and inline inspection, the line reached 98% uptime after commissioning with daily output matching the plant''s needs. The customer highly praised equipment stability and Yinkai''s remote support, and both parties reached preliminary intent for phase-two expansion.'),
(8,'技术迭代','Technology','2024-06-15','YK-FC 复合材料产线实现多材质兼容切换','YK-FC Composite Lines Now Support Multi-Material Quick Changeover','换型时间缩短至 20 分钟以内，支持玻纤/聚氨酯共线生产。','Changeover under 20 minutes, supporting fiberglass/PU co-production.','YK-FC 系列复合材料边框自动生产线完成技术升级，实现玻纤、聚氨酯等多材质边框的共线兼容生产，换型时间缩短至 20 分钟以内。升级后的产线在保证 ±0.15mm 加工精度的同时，可满足组件客户小批量、多品种的柔性生产需求，已在多家客户现场稳定运行。','The YK-FC composite frame line series has been upgraded for co-production of fiberglass and polyurethane frames, cutting changeover to under 20 minutes. While maintaining ±0.15mm precision, the upgraded line meets customers'' flexible needs for small-batch, multi-variety production and has been running stably at multiple customer sites.'),
(9,'展会活动','Exhibitions','2024-05-20','SNEC 光伏展完美收官，现场达成多项合作意向','SNEC PV Power Expo Concluded with Multiple Cooperation Intentions','YK 系列全线产品集中亮相，观众超十万人次。','Full YK lineup on show with over 100,000 visitors.','寅铠携 YK 系列光伏边框自动生产线、视觉检测系统等全线产品亮相 SNEC 国际太阳能光伏与智慧能源大会。展台现场观众超十万人次，团队与数十家组件企业就产线规划、设备升级展开深入交流，达成多项合作意向。展会期间发布的 YK-7 系列新一代高速产线成为全场焦点。','Yinkai showcased its full YK series — PV frame automatic lines and vision inspection systems — at the SNEC International Solar PV & Smart Energy Conference. The booth attracted over 100,000 visitors. The team held in-depth exchanges with dozens of module companies on line planning and upgrades, reaching multiple cooperation intentions. The newly released YK-7 high-speed line series was a highlight of the show.'),
(10,'质量体系','Quality','2024-02-28','获得高新技术企业认定，研发投入持续加码','Certified as High-Tech Enterprise with Rising R&D Investment','累计授权专利 60 余项，研发人员占比超 30%。','60+ patents granted; R&D staff over 30% of headcount.','寅铠顺利通过国家高新技术企业认定。公司累计获得授权专利 60 余项，其中发明专利占比持续提升；研发人员占员工总数超过 30%。未来公司将持续加大在视觉检测算法、高速运动控制与产线数字化方向的研发投入，为客户提供更具竞争力的智能制造装备。','Yinkai officially obtained the national High-Tech Enterprise certification. The company holds 60+ granted patents with a rising share of invention patents, and R&D staff account for over 30% of the workforce. Yinkai will continue increasing investment in vision inspection algorithms, high-speed motion control and line digitalization to deliver more competitive smart manufacturing equipment.'),
(11,'公司动态','Company News','2023-11-08','二期厂房扩建竣工，产能迈上新台阶','Phase-II Plant Expansion Completed, Capacity on a New Level','新增装配工位 20 余个，年交付产线能力提升 40%。','20+ new assembly stations; annual line delivery up 40%.','寅铠二期厂房扩建工程正式竣工投用，新增标准化装配工位 20 余个、大型加工设备 8 台，年交付产线能力提升约 40%。新厂房配备整机老化测试区与模拟产线验证区，出厂前可对整线进行 72 小时连续运行测试，进一步保障交付设备的可靠性。','Yinkai''s phase-II plant expansion has been completed and put into operation, adding 20+ standardized assembly stations and 8 large machining machines, raising annual line delivery capacity by about 40%. The new plant features an aging test area and a simulated line validation zone, allowing 72-hour continuous full-line testing before shipment to further ensure delivery reliability.'),
(12,'项目交付','Project Delivery','2023-07-12','中东光伏产业园项目顺利投产','Middle East PV Industrial Park Project Commissioned','高温环境定制设计，连续运行稳定性获客户认可。','Custom design for high-temperature environments earns recognition.','寅铠为中东某光伏产业园定制设计的边框自动生产线顺利投产。针对当地高温、高粉尘环境，产线在散热系统、密封防护与除尘结构上做了专项设计，投产后连续运行稳定，各项指标达到合同要求。该项目的落地进一步拓展了公司在“一带一路”沿线市场的布局。','The customized PV frame automatic lines supplied by Yinkai for a PV industrial park in the Middle East were successfully commissioned. Special designs for cooling, sealing and dust protection were made for the local high-temperature, high-dust environment. The line has been running stably since commissioning with all indicators meeting contract requirements, further expanding Yinkai''s presence along the Belt and Road markets.');

-- ---- 职位 ----
INSERT INTO jobs (id, title_zh, title_en, dept_zh, dept_en, location_zh, location_en, desc_zh, desc_en) VALUES
(1,'机械设计工程师','Mechanical Design Engineer','研发中心','R&D Center','上海·安亭','Anting, Shanghai','岗位职责：负责非标自动化设备与产线的机械结构设计方案、图纸绘制及 BOM 编制，跟进装配调试并持续优化结构。\n任职要求：机械设计及相关专业，熟练使用 SolidWorks / AutoCAD，三年以上非标自动化设计经验，熟悉钣金、机加工工艺。','Responsibilities: Design mechanical structures for custom automation equipment and lines, produce drawings and BOMs, and support assembly, commissioning and optimization.\nRequirements: Degree in mechanical design or related field; proficient in SolidWorks / AutoCAD; 3+ years of non-standard automation design experience; familiar with sheet-metal and machining processes.'),
(2,'电气调试工程师','Electrical Commissioning Engineer','工程部','Engineering','上海·安亭','Anting, Shanghai','岗位职责：负责自动化产线电气原理设计、PLC 程序编写与现场调试，配合机械完成整线联调并交付客户。\n任职要求：电气自动化相关专业，熟悉西门子 / 三菱 PLC 与伺服系统，能适应出差，有产线整线调试经验者优先。','Responsibilities: Design electrical schematics for automation lines, write PLC programs, commission on site and support full-line integration and customer delivery.\nRequirements: Degree in electrical automation; familiar with Siemens / Mitsubishi PLC and servo systems; willing to travel; line commissioning experience preferred.'),
(3,'视觉算法工程师','Vision Algorithm Engineer','研发中心','R&D Center','上海·安亭','Anting, Shanghai','岗位职责：负责视觉检测系统的图像算法开发与优化（尺寸测量、外观瑕疵识别、分类分拣），跟进现场调试与算法迭代。\n任职要求：计算机 / 光电 / 自动化相关专业，熟练使用 OpenCV / Halcon，有深度学习瑕疵检测项目经验者优先。','Responsibilities: Develop and optimize image algorithms for vision inspection (dimension measurement, defect recognition and sorting), and iterate on-site.\nRequirements: Degree in CS / optoelectronics / automation; proficient in OpenCV / Halcon; deep-learning defect detection project experience preferred.'),
(4,'测量工程师（FARO）','Metrology Engineer (FARO)','质量部','Quality','上海·安亭','Anting, Shanghai','岗位职责：使用 FARO 激光跟踪仪、关节臂等设备开展精密测量与数据分析，出具检测报告，参与设备精度验收。\n任职要求：测量 / 机械相关专业，熟悉 FARO 设备与三维测量软件，细心严谨，具备 ±0.1mm 级精度检测经验者优先。','Responsibilities: Perform precision measurement and data analysis with FARO laser trackers and measuring arms, issue inspection reports and join equipment accuracy acceptance.\nRequirements: Degree in metrology / mechanical engineering; familiar with FARO devices and 3D inspection software; detail-oriented; ±0.1mm-level inspection experience preferred.'),
(5,'装配钳工','Assembly Fitter','生产部','Production','上海·安亭','Anting, Shanghai','岗位职责：按图纸完成自动化设备的机械装配、调试与出厂检验，配合现场安装与售后支持。\n任职要求：有钳工装配经验，能识读机械图纸，熟练使用各类量具与装配工具，责任心强，能配合出差。','Responsibilities: Assemble and commission automation equipment per drawings, carry out factory inspection, and support on-site installation and after-sales.\nRequirements: Fitting and assembly experience; able to read mechanical drawings; skilled with measuring and assembly tools; responsible and willing to travel.'),
(6,'国际销售工程师','International Sales Engineer','销售部','Sales','上海·安亭','Anting, Shanghai','岗位职责：负责海外市场开拓与客户维护，参与技术方案沟通、报价与商务谈判，跟进项目签约与回款。\n任职要求：本科及以上，英语流利（可海外出差），了解光伏或汽车装备行业者优先，具备良好的沟通与抗压能力。','Responsibilities: Develop overseas markets and maintain client relationships, join technical discussions, quotations and negotiations, and follow up on contracts and payments.\nRequirements: Bachelor degree or above; fluent English and willing to travel abroad; PV or automotive equipment industry knowledge preferred; strong communication skills.');

-- ---- 产品分类 ----
INSERT INTO product_categories (id, slug, name_zh, name_en, desc_zh, desc_en, sort) VALUES
(1,'pv-alu','光伏边框铝型材自动生产线','PV Frame Aluminium Profile Lines','面向长边/短边铝型材边框的自动冲切、铆接全线装备，自动送料、切割、冲压、铆接、检测全流程覆盖。','Complete lines for long/short aluminium PV frames covering auto feeding, cutting, stamping, riveting and inspection.',1),
(2,'pv-fc','光伏边框复合材料自动生产线','PV Frame Composite Material Lines','复合材料边框长边/短边自动线与角码装配机，精度 ±0.15mm，稼动率 98%。','Long/short-edge composite frame lines and corner-key assembly machines with ±0.15mm precision and 98% uptime.',2),
(3,'stacker','自动码垛机','Automatic Stacking Machines','长边/短边边框成品自动码垛，替代人工整理，稼动率 98%。','Automatic stacking of long/short finished frames, replacing manual handling, 98% uptime.',3),
(4,'feeder','自动上料机','Automatic Feeding Machine','边框原材料自动上料与缓存，保障深加工设备连续生产。','Automatic feeding and buffering of frame raw material for continuous downstream production.',4),
(5,'vision','自动视觉检测系统','Automatic Vision Inspection','在线/离线视觉检测，十余类瑕疵自动识别分拣，检测数据全程可追溯。','Inline/offline vision inspection with auto sorting of a dozen-plus defect types and full traceability.',5),
(6,'automotive','汽车轻量化设备','Automotive Lightweight Equipment','面向车身轻量化结构件的型材成形与连接装备，支持 FSW 搅拌摩擦焊与 CMT 冷金属过渡焊工艺。','Forming and joining equipment for lightweight automotive structures, supporting FSW and CMT welding processes.',6);

-- ---- 产品(image 存文件名) ----
INSERT INTO products (id, category_id, model, tag_zh, tag_en, image, gallery, desc_zh, desc_en, sort) VALUES
(1,1,'YK-6A','立冲长边','Vertical Punch, Long Edge','yk-6a_banner.png',NULL,'适用边框长度 1500-2600mm，节拍 1.8-2.1 秒/支，12 小时产能 18000-20000 支，加工精度 ±0.1mm，稼动率 98%。','For 1500-2600mm frames at 1.8-2.1s per piece, 18,000-20,000 pcs per 12h, ±0.1mm precision, 98% uptime.',1),
(2,1,'YK-6B','卧冲短边','Horizontal Punch, Short Edge','yk-6b_banner.jpg',NULL,'适用边框长度 850-1500mm，节拍 1.8-2.1 秒/支，12 小时产能 18000-20000 支，加工精度 ±0.1mm，稼动率 98%。','For 850-1500mm frames at 1.8-2.1s per piece, 18,000-20,000 pcs per 12h, ±0.1mm precision, 98% uptime.',2),
(3,1,'YK-6W','卧冲长边','Horizontal Punch, Long Edge','yk-6w_banner.jpg',NULL,'适用边框长度 1500-2600mm，节拍 1.8-2.1 秒/支，加工精度 ±0.1mm，稼动率 98%，装机容量 10.8 吨。','For 1500-2600mm frames at 1.8-2.1s per piece, ±0.1mm precision, 98% uptime, 10.8t overall weight.',3),
(4,2,'YK-FC-3C','长边自动线','Long-Edge Line','yk-fc-3c_banner.jpg',NULL,'适用边框长度 1500-2600mm，加工精度 ±0.15mm，45° 切角精度，稼动率 98%。','For 1500-2600mm composite frames, ±0.15mm precision with 45° mitre accuracy, 98% uptime.',1),
(5,2,'YK-FC-3D','短边自动线','Short-Edge Line','yk-fc-3d_banner.jpg',NULL,'适用边框长度 850-1500mm，结构紧凑，稼动率 98%，装机容量 8.3 吨。','For 850-1500mm frames in a compact footprint, 98% uptime, 8.3t overall weight.',2),
(6,2,'YK-FC-3J','角码装配机','Corner-Key Assembly Machine','yk-fc-3j_banner.jpg',NULL,'边框角码自动装配，外形 4500×3800×1500mm，装机容量仅 1.5 吨，稼动率 98%。','Automatic corner-key assembly, footprint 4500×3800×1500mm, only 1.5t overall weight, 98% uptime.',3),
(7,3,'YK-3E','长边自动码垛机','Long-Edge Stacker','yk-3e_banner.jpg',NULL,'适用 1500-2600mm 长边框自动码垛，外形 7000×6300×2500mm，稼动率 98%。','Automatic stacking for 1500-2600mm long frames, footprint 7000×6300×2500mm, 98% uptime.',1),
(8,3,'YK-3F','短边自动码垛机','Short-Edge Stacker','yk-3f_banner.jpg',NULL,'适用 850-1500mm 短边框自动码垛，外形 5000×7200×2500mm，稼动率 98%。','Automatic stacking for 850-1500mm short frames, footprint 5000×7200×2500mm, 98% uptime.',2),
(9,4,'YK-AL-1','桁架式自动上料','Gantry-Type Auto Feeding','yk-al-1_banner.png',NULL,'适用原料长 3900-7500mm、宽 30-45mm、高 11-35mm；最大承重 3000kg（含托盘），托盘存放 360 支，上料节拍 2 秒/支，缓冲区可存 50 支确保不停机换框，稼动率 ≥85%。','For raw material 3900-7500mm long, 30-45mm wide, 11-35mm high; 3000kg max load (incl. pallet), 360 pcs per pallet, 2s feeding cycle, 50-pc buffer for non-stop changeover, ≥85% uptime.',1),
(10,5,'YK-OL-2I','在线视觉检测','Inline Inspection','yk-ol-2i_banner.png','["1.png","2.png","3.png","4.png","5.png"]','设备与上一工位对接，加工后的产品自动输送到设备内部待检测，本设备自动检测产品的长度、漏加工、外观瑕疵。检测后的产品自动分类输送到下一工位。','Docking with the upstream station, processed products are automatically conveyed inside for inspection. The machine automatically checks length, missed operations and surface defects, then sorts and conveys products to the next station.',1),
(11,5,'YK-OF-3I','离线视觉检测','Offline Inspection','yk-ol-3i_banner.png',NULL,'离线式检测站，外形 3900×1550×2500mm，全尺寸检测并自动生成可追溯报告。','Offline inspection station, footprint 3900×1550×2500mm, full-size inspection with traceable reports.',2),
(12,6,'型材拉弯机','型材拉弯成形','Profile Stretch Bending','yk-xingcailawanji_banner.png',NULL,'适用型材宽度 900-3200mm，拉弯速度 0-100mm/s，成形精度 0.02mm，单件节拍约 40 秒。','For profiles 900-3200mm wide, bending speed 0-100mm/s, 0.02mm forming precision, ~40s per piece.',1),
(13,6,'自动锁螺母生产线','螺母自动压装','Nut Auto-Insertion Line','yk-zidongsuoluomushengchanxian_banner.jpg',NULL,'轻量化结构件螺母自动锁定生产线，配合 FSW/CMT 焊接工艺，服务汽车白车身轻量化制造。','Automatic nut-insertion line for lightweight structures with FSW/CMT welding, serving BIW lightweight manufacturing.',2);

-- ---- 产品参数 ----
INSERT INTO product_params (product_id, label_zh, label_en, value_zh, value_en, sort) VALUES
(1,'名称','Name','铝材长边立冲生产线','Aluminium long-edge vertical-punch line',1),
(1,'加工范围 mm','Processing Range','1500-2600','1500-2600',2),
(1,'原材料兼容尺寸(长度)','Raw Material Length','≤7.5m','≤7.5m',3),
(1,'生产节拍(支/秒)','Production Cycle','1.8-2.1(18000-20000支/12H)','1.8-2.1s (18,000-20,000 pcs/12H)',4),
(1,'长度切割精度 mm','Cutting Accuracy','±0.1','±0.1',5),
(1,'孔距精度 mm','Hole Pitch Accuracy','±0.1','±0.1',6),
(1,'切角角度','Mitre Angle','35°-55°可调','35°-55° adjustable',7),
(1,'角度切割精度','Angle Accuracy','±0.1°','±0.1°',8),
(1,'铆点精度 mm','Riveting Accuracy','±0.1','±0.1',9),
(1,'换模时间','Changeover Time','<2H','<2H',10),
(1,'无故障运行率','Uptime','98%','98%',11),
(1,'装机容量 KW','Installed Capacity','28','28',12),
(1,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','10700×6300×2300','10700×6300×2300',13),
(1,'气源电力源','Air Supply','2300L/min 5.0-6.0kgf/cm²','2300L/min 5.0-6.0kgf/cm²',14),
(1,'设备电源','Power Supply','380V 50HZ','380V 50HZ',15),
(1,'控制系统电源','Control Power','DC24V','DC24V',16),
(1,'设备重量 T','Net Weight','14.8','14.8',17),
(1,'设备方向','Layout Orientation','可选择对称方向','Symmetric orientation optional',18),
(2,'名称','Name','铝材短边卧冲生产线','Aluminium short-edge horizontal-punch line',1),
(2,'加工范围 mm','Processing Range','850-1500','850-1500',2),
(2,'原材料兼容尺寸(长度)','Raw Material Length','≤7.5m','≤7.5m',3),
(2,'生产节拍(支/秒)','Production Cycle','1.8-2.1(18000-20000支/12H)','1.8-2.1s (18,000-20,000 pcs/12H)',4),
(2,'长度切割精度 mm','Cutting Accuracy','±0.1','±0.1',5),
(2,'孔距精度 mm','Hole Pitch Accuracy','±0.1','±0.1',6),
(2,'切角角度','Mitre Angle','35°-55°可调','35°-55° adjustable',7),
(2,'角度切割精度','Angle Accuracy','±0.1°','±0.1°',8),
(2,'铆点精度 mm','Riveting Accuracy','±0.1','±0.1',9),
(2,'换模时间','Changeover Time','<2H','<2H',10),
(2,'无故障运行率','Uptime','98%','98%',11),
(2,'装机容量 KW','Installed Capacity','27','27',12),
(2,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','10700×7070×2300','10700×7070×2300',13),
(2,'气源电力源','Air Supply','2300L/min 5.0-6.0kgf/cm²','2300L/min 5.0-6.0kgf/cm²',14),
(2,'设备电源','Power Supply','380V 50HZ','380V 50HZ',15),
(2,'控制系统电源','Control Power','DC24V','DC24V',16),
(2,'设备重量 T','Net Weight','11.7','11.7',17),
(2,'设备方向','Layout Orientation','可选择对称方向','Symmetric orientation optional',18),
(3,'名称','Name','铝材长边卧冲生产线','Aluminium long-edge horizontal-punch line',1),
(3,'加工范围 mm','Processing Range','1500-2600','1500-2600',2),
(3,'原材料兼容尺寸(长度)','Raw Material Length','≤7.5m','≤7.5m',3),
(3,'生产节拍(支/秒)','Production Cycle','1.8-2.1(18000-20000支/12H)','1.8-2.1s (18,000-20,000 pcs/12H)',4),
(3,'长度切割精度 mm','Cutting Accuracy','±0.1','±0.1',5),
(3,'孔距精度 mm','Hole Pitch Accuracy','±0.1','±0.1',6),
(3,'切角角度','Mitre Angle','35°-55°可调','35°-55° adjustable',7),
(3,'角度切割精度','Angle Accuracy','±0.1°','±0.1°',8),
(3,'铆点精度 mm','Riveting Accuracy','±0.1','±0.1',9),
(3,'换模时间','Changeover Time','<2H','<2H',10),
(3,'无故障运行率','Uptime','98%','98%',11),
(3,'装机容量 KW','Installed Capacity','28','28',12),
(3,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','10700×6300×2300','10700×6300×2300',13),
(3,'气源电力源','Air Supply','2300L/min 5.0-6.0kgf/cm²','2300L/min 5.0-6.0kgf/cm²',14),
(3,'设备电源','Power Supply','380V 50HZ','380V 50HZ',15),
(3,'控制系统电源','Control Power','DC24V','DC24V',16),
(3,'设备重量 T','Net Weight','10.8','10.8',17),
(3,'设备方向','Layout Orientation','可选择对称方向','Symmetric orientation optional',18),
(4,'名称','Name','复合材料长边自动生产线','Composite long-edge automatic line',1),
(4,'加工范围 mm','Processing Range','1500-2600','1500-2600',2),
(4,'原材料兼容尺寸(长度)','Raw Material Length','≤7.5m','≤7.5m',3),
(4,'生产节拍(支/秒)','Production Cycle','4.5','4.5',4),
(4,'长度切割精度 mm','Cutting Accuracy','±0.15','±0.15',5),
(4,'孔距精度 mm','Hole Pitch Accuracy','±0.15','±0.15',6),
(4,'切角角度','Mitre Angle','45°','45°',7),
(4,'角度切割精度','Angle Accuracy','-0.3°~0°','-0.3°~0°',8),
(4,'换模时间','Changeover Time','3H','3H',9),
(4,'无故障运行率','Uptime','98%','98%',10),
(4,'装机容量 KW','Installed Capacity','28','28',11),
(4,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','10700×6200×2400','10700×6200×2400',12),
(4,'气源电力源','Air Supply','2000L/min 5.0-6.0kgf/cm²','2000L/min 5.0-6.0kgf/cm²',13),
(4,'设备电源','Power Supply','380V 50HZ','380V 50HZ',14),
(4,'控制系统电源','Control Power','DC24V','DC24V',15),
(4,'设备重量 T','Net Weight','9.5','9.5',16),
(5,'名称','Name','复合材料短边自动生产线','Composite short-edge automatic line',1),
(5,'加工范围 mm','Processing Range','850-1500','850-1500',2),
(5,'生产节拍(支/秒)','Production Cycle','1.7','1.7',3),
(5,'换模时间','Changeover Time','0.5H','0.5H',4),
(5,'无故障运行率','Uptime','98%','98%',5),
(5,'装机容量 KW','Installed Capacity','11','11',6),
(5,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','10700×12700×2400','10700×12700×2400',7),
(5,'气源电力源','Air Supply','500L/min 5.0-6.0kgf/cm²','500L/min 5.0-6.0kgf/cm²',8),
(5,'设备电源','Power Supply','380V 50HZ','380V 50HZ',9),
(5,'控制系统电源','Control Power','DC24V','DC24V',10),
(5,'设备重量 T','Net Weight','8.3','8.3',11),
(6,'名称','Name','复合材料角码装配机','Composite corner-key assembly machine',1),
(6,'加工范围 mm','Processing Range','850-1500','850-1500',2),
(6,'生产节拍(支/秒)','Production Cycle','2.5','2.5',3),
(6,'换模时间','Changeover Time','0.5H','0.5H',4),
(6,'无故障运行率','Uptime','98%','98%',5),
(6,'装机容量 KW','Installed Capacity','6','6',6),
(6,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','4500×3800×1500','4500×3800×1500',7),
(6,'气源电力源','Air Supply','200L/min 5.0-8.0kgf/cm²','200L/min 5.0-8.0kgf/cm²',8),
(6,'设备电源','Power Supply','380V 50HZ','380V 50HZ',9),
(6,'控制系统电源','Control Power','DC24V','DC24V',10),
(6,'设备重量 T','Net Weight','1.5','1.5',11),
(7,'名称','Name','长边自动码垛机','Long-edge automatic stacker',1),
(7,'加工范围 mm','Processing Range','1500-2600','1500-2600',2),
(7,'生产节拍(支/秒)','Production Cycle','1.7','1.7',3),
(7,'换模时间','Changeover Time','0.5H','0.5H',4),
(7,'无故障运行率','Uptime','98%','98%',5),
(7,'装机容量 KW','Installed Capacity','11','11',6),
(7,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','7000×6300×2500','7000×6300×2500',7),
(7,'气源电力源','Air Supply','500L/min 5.0-6.0kgf/cm²','500L/min 5.0-6.0kgf/cm²',8),
(7,'设备电源','Power Supply','380V 50HZ','380V 50HZ',9),
(7,'控制系统电源','Control Power','DC24V','DC24V',10),
(7,'设备重量 T','Net Weight','4.2','4.2',11),
(8,'名称','Name','短边自动码垛机','Short-edge automatic stacker',1),
(8,'加工范围 mm','Processing Range','850-1500','850-1500',2),
(8,'生产节拍(支/秒)','Production Cycle','2','2',3),
(8,'换模时间','Changeover Time','0.5H','0.5H',4),
(8,'无故障运行率','Uptime','98%','98%',5),
(8,'装机容量 KW','Installed Capacity','11','11',6),
(8,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','5000×7200×2500','5000×7200×2500',7),
(8,'气源电力源','Air Supply','500L/min 5.0-6.0kgf/cm²','500L/min 5.0-6.0kgf/cm²',8),
(8,'设备电源','Power Supply','380V 50HZ','380V 50HZ',9),
(8,'控制系统电源','Control Power','DC24V','DC24V',10),
(8,'设备重量 T','Net Weight','3.7','3.7',11),
(9,'名称','Name','自动上料机','Automatic feeding machine',1),
(9,'适用边框原材料尺寸','Raw Material Size','长 3900-7500mm，宽 30-45mm，高 11-35mm','L 3900-7500mm, W 30-45mm, H 11-35mm',2),
(9,'最大重量(含托盘)','Max Load (incl. pallet)','3000kg','3000kg',3),
(9,'托盘原材料存放数量','Pallet Capacity','360 支','360 pcs',4),
(9,'上料节拍','Feeding Cycle','2 秒/支','2s per pc',5),
(9,'上料缓冲区','Feed Buffer','≥50 支','≥50 pcs',6),
(9,'设备稼动率','Uptime','≥85%','≥85%',7),
(9,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','8000×6500×3000','8000×6500×3000',8),
(10,'名称','Name','在线视觉检测系统','Inline vision inspection system',1),
(10,'检测方式','Inspection Mode','产线在线全检','Inline full inspection',2),
(10,'检测项目','Inspection Items','长度、扭曲度、漏加工及碰伤、划伤、变形等十余类','Length, twist, missed ops, dents, scratches, deformation and more',3),
(10,'生产节拍(支/秒)','Production Cycle','≤1.7','≤1.7',4),
(10,'换型时间','Changeover Time','≤20 分钟','≤20 min',5),
(10,'分拣方式','Sorting','OK/NG 自动分拣','Automatic OK/NG sorting',6),
(10,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','3550×2900×2500','3550×2900×2500',7),
(11,'名称','Name','离线视觉检测系统','Offline vision inspection system',1),
(11,'检测方式','Inspection Mode','离线全尺寸检测','Offline full-size inspection',2),
(11,'检测项目','Inspection Items','长度、角度、卡槽、冲孔、铆压等','Length, angle, slots, punching, riveting, etc.',3),
(11,'生产节拍','Cycle Time','约 1 分钟/件','~1 min per pc',4),
(11,'检测报告','Reports','自动打印,结果长期可追溯','Auto-printed, long-term traceable',5),
(11,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','3900×1550×2500','3900×1550×2500',6),
(12,'名称','Name','型材拉弯机','Profile stretch-bending machine',1),
(12,'适用型材宽度 mm','Profile Width','900-3200','900-3200',2),
(12,'拉弯速度','Bending Speed','0-100mm/s','0-100mm/s',3),
(12,'单件节拍','Cycle Time','约 40 秒','~40s',4),
(12,'成形精度 mm','Forming Accuracy','0.02','0.02',5),
(12,'弯曲角度范围','Bending Angle Range','5°-85°','5°-85°',6),
(12,'装机容量 KVA','Installed Capacity','75','75',7),
(12,'设备电源','Power Supply','380V±10% 50-60HZ','380V±10% 50-60HZ',8),
(12,'无故障运行率','Uptime','99.8%','99.8%',9),
(12,'外形尺寸mm(长×宽×高)','Dimensions (L×W×H)','6300×1200×1800','6300×1200×1800',10),
(13,'名称','Name','自动锁螺母生产线','Automatic nut-insertion line',1),
(13,'工艺支持','Processes','FSW 搅拌摩擦焊 / CMT 冷金属过渡焊','FSW / CMT welding',2),
(13,'应用领域','Application','汽车白车身轻量化结构件','BIW lightweight structures',3),
(13,'生产方式','Production Mode','自动上料 + 锁螺母 + 焊接集成','Integrated feeding, nut insertion and welding',4);

-- ---- 荣誉(image 存文件名) ----
INSERT INTO honors (name_zh, name_en, desc_zh, desc_en, image, sort) VALUES
('综合资质证书','Certificates Overview','高新技术企业、安全生产标准化、SEC 年度确认及多项专利证书。','High-tech enterprise, work safety standardization, SEC annual confirmation and multiple patents.','honor-01.jpg',1),
('上海市“专精特新”中小企业','Shanghai \"Specialized & Innovative\" SME','上海市经济和信息化委员会认定,聚焦细分领域的专业化标杆。','Recognized by Shanghai SME Commission as a specialized and innovative enterprise.','honor-02.jpg',2),
('质量管理体系认证','QMS Certification','通过 SEC 质量管理体系认证,质量管理与国际接轨。','Certified quality management system (SEC), aligned with international standards.','honor-03.jpg',3),
('ISO Quality Certification','ISO Quality Certification','面向国际客户的质量管理体系认证(英文版)。','Quality management system certification for international clients.','honor-04.jpg',4),
('安全生产标准化三级企业','Work Safety Standardization Level 3','机械行业安全生产标准化三级企业认证。','Level-3 work safety standardization (machinery industry).','honor-05.jpg',5),
('实用新型专利证书','Utility Model Patents','拥有多项实用新型专利,覆盖光伏边框生产与检测设备。','Multiple utility model patents covering PV frame production and inspection equipment.','honor-06.jpg',6),
('专利登记簿副本','Patent Register','国家知识产权局专利登记簿副本,专利权属清晰可查。','Patent register copies from CNIPA with clear ownership records.','honor-07.jpg',7);

-- ---- 合作伙伴(image 存文件名) ----
INSERT INTO partners (slug, name_zh, name_en, image, sort) VALUES
('xinbo','鑫铂股份','Xinbo Co.','p1.png',1),
('jinkosolar','晶科能源','JinkoSolar','p2.png',2),
('deyilong','德毅隆','Deyilong','p3.png',3),
('cirs','CIRS','CIRS','p4.png',4),
('hongsheng','鸿盛','Hongsheng','p5.png',5),
('jinkopower','晶科科技','JinkoPower','p6.png',6),
('kejing','合肥科晶','Hefei Kejing','p7.png',7),
('akcome','爱康集团','AKCOME Group','p8.png',8),
('ysmetal','源盛金属','YuanSheng Metal','p9.png',9),
('yuansheng','源盛','Yuansheng','p10.png',10),
('krant','科蓝特','Krant','p11.png',11),
('freemt','复睿金属','FreeMt Metal','p12.png',12),
('yuejia','江苏月嘉金属','Jiangsu Yuejia Metal','p13.png',13),
('shengxin','生信','Shengxin','p14.png',14),
('gaoling','高瓴新材料','Gaoling New Materials','p15.png',15),
('aina','艾纳新能源','Aina New Energy','p16.png',16),
('partner17','合作伙伴','Partner','p17.png',17),
('arctech','中信博','Arctech','p18.png',18),
('pingmei','平煤隆基','Pingmei Longji','p19.png',19),
('chuangjia','创佳型材','Chuangjia','p20.png',20);
